### ISSUE TITLE
Issues with errors.R

### ISSUE THREAD

**Issue by jpgattuso** [jpgattuso/seacarb-git#25]
@jamesorr 

Jim,

I am working on the Point B manuscript and would like to include some information about uncertainties. Submission is planned at the end of August will it be possible to use the new error function?

In any case, I found issues working on the data set (link below).

- the errors function breaks when one uses ePk=NULL as you do by default. Perhaps you should use if(is.null(ePk))...  to bring in the default values (which should be mentioned, with the source, in errors.Rd.
- I think the units are not mol/kg as indicated in the errors man file are they mol/kg
- In the attached, you will find a short R script for testing. It should be self-explanatory. You will just need to install the dplyr package if you do not use it.

We can speak on the phone if needed.

[Archive.zip](https://github.com/jpgattuso/seacarb-git/files/409024/Archive.zip)

**Comment by jamesorr** [comment]
No problem to use the error routines in your new manuscript.  It might be best though not to provide much detail regarding the technique. 

Your 3 points should be resolved if you implement the just-submitted Pull request #26 . That is

- the errors function can now be used with epK=NULL, with epK=0, or without giving a value of epK;
- the units are indeed mol/kg as mentioned in the errors.Rd man file (the problem was that your input was given in umol/kg for the errors); and 
- a modified version of your R script is attached--it has also been simplified and it seems to work fine now.

[errors_test_gattuso.zip](https://github.com/jpgattuso/seacarb-git/files/416134/errors_test_gattuso.zip)

**Comment by jpgattuso** [comment]
Jim,

I feel stupid that I used errors in mol/kg... I will look into the 
revised package next week.

Bon week end,
Jean-Pierre


On 12 Aug 2016, at 22:37, James Orr wrote:

> No problem to use the error routines in your new manuscript. It might 
> be best though not to provide much detail regarding the technique. 


----
Jean-Pierre Gattuso | http://www.obs-vlfr.fr/~gattuso | @jpGattuso

**Comment by jamesorr** [comment]
It is not stupid. Rather it is a common error that many users may make in the future.  Can you think of a way to make the routines more bulletproof for such 'obvious' errors in input.

> the errors function can now be used with epK=NULL, with epK=0, or without giving a value of epK;

I forgot to mention that the 'errors' routine was also modified so that when the epK argument is not provided, the default is now to use the standard set of uncertainties as documented in the modified 'errors.Rd' man file.
