### ISSUE TITLE
Recent changes 3.1.2

### ISSUE THREAD

**Issue by jpgattuso** [jpgattuso/seacarb-git#37]
Dear Jim,

I do not understand the logic of the changes made on function error. Why is the uncertainty of the boron concentration considered as a dissociation constant and include in 
I suggest instead to consider eBt, on it own as is done with ePt and eSit

The function currently looks like this:
errors <- 
function(flag, var1, var2, S=35, T=25, Patm=1, P=0, Pt=0, Sit=0, 
         evar1=0, evar2=0, eS=0.01, eT=0.01, ePt=0, eSit=0, epK=c(0.004, 0.015, 0.03, 0.01, 0.01, 0.02, 0.02, 0.01), 
         method="ga", r=0, runs=10000, 
         k1k2='x', kf='x', ks="d", pHscale="T", b="u74", gas="potential", warn="y")

Perhaps the following would be better:
errors <- 
function(flag, var1, var2, S=35, T=25, Patm=1, P=0, Pt=0, Sit=0, 
         evar1=0, evar2=0, eS=0.01, eT=0.01, ePt=0, eSit=0, eBt= 0.01, epK=c(0.004, 0.015, 0.03, 0.01, 0.01, 0.02, 0.02), 
         method="ga", r=0, runs=10000, 
         k1k2='x', kf='x', ks="d", pHscale="T", b="u74", gas="potential", warn="y")

Am I missing something? Please use the new branch 3.1.2 to make the changes.

Best,
Jean-Pierre

**Comment by jamesorr** [comment]
Hi Jean-Pierre,

When adding eBt to the errors function, my idea was to include it in the constants vector for 3 reasons:
(1) its uncertainty refers to a type of constant (although not an equilibrium constant) rather than to something the user has measured (e.g., eP and eSit), i.e., eBt  is refers to the boron-to-salinity ratio;
(2) it seemed better to represent eBt as a percent relative error, while the other individual errors (evar1, evar2, eS, eT, ePt, eSit) are all absolute errors;
(3) it seems we already have too many input arguments, and *hiding* Bt in the uncertainty vector for the constants was a way to get it out of the way (into a zone that most users will probably want to avoid touching anyway).

**Comment by jamesorr** [comment]
Jean-Pierre,
For improved consistency, we should follow your 2 suggestions
- to remove eBt from the epK vector and 
- to add it as a separate argument, 

BUT I suggest that we should also change its name to  'reBt'  to signify that it is given with a different convention (relative error instead of absolute error).
What do you think?

**Comment by jpgattuso** [comment]
Hi Jim,

I agree. Let’s do that despite the fact that it is one more parameter 
to add to the function…

Cheers,
Jean-Pierre

On 24 Jan 2017, at 9:53, James Orr wrote:

> Jean-Pierre,
> For improved consistency, we should follow your 2 suggestions
> - to remove eBt from the epK vector and
> - to add it as a separate argument,
>
> BUT I suggest that we should also change its name to  'reBt'  to 
> signify that it is given with a different convention (relative error 
> instead of absolute error).
> What do you think?
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jpgattuso/seacarb-git/issues/37#issuecomment-274744531




---------------------------------------------
Jean-Pierre Gattuso | http://www.obs-vlfr.fr/~gattuso | @jpGattuso
